/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthenticatedManageHousesRouteImport } from './routes/_authenticated/manage-houses'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedHSlugRouteImport } from './routes/_authenticated/h/$slug'
import { Route as AuthenticatedAccountHousesSlugRouteImport } from './routes/_authenticated/account/houses/$slug'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthenticatedManageHousesRoute =
  AuthenticatedManageHousesRouteImport.update({
    id: '/manage-houses',
    path: '/manage-houses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHSlugRoute = AuthenticatedHSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountHousesSlugRoute =
  AuthenticatedAccountHousesSlugRouteImport.update({
    id: '/account/houses/$slug',
    path: '/account/houses/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/manage-houses': typeof AuthenticatedManageHousesRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/h/$slug': typeof AuthenticatedHSlugRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/account/houses/$slug': typeof AuthenticatedAccountHousesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/manage-houses': typeof AuthenticatedManageHousesRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/h/$slug': typeof AuthenticatedHSlugRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/account/houses/$slug': typeof AuthenticatedAccountHousesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_authenticated/manage-houses': typeof AuthenticatedManageHousesRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/h/$slug': typeof AuthenticatedHSlugRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/account/houses/$slug': typeof AuthenticatedAccountHousesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage-houses'
    | '/sign-in'
    | '/sign-up'
    | '/h/$slug'
    | '/account/'
    | '/account/houses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage-houses'
    | '/sign-in'
    | '/sign-up'
    | '/h/$slug'
    | '/account'
    | '/account/houses/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/manage-houses'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/_authenticated/'
    | '/_authenticated/h/$slug'
    | '/_authenticated/account/'
    | '/_authenticated/account/houses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authenticated/manage-houses': {
      id: '/_authenticated/manage-houses'
      path: '/manage-houses'
      fullPath: '/manage-houses'
      preLoaderRoute: typeof AuthenticatedManageHousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/h/$slug': {
      id: '/_authenticated/h/$slug'
      path: '/h/$slug'
      fullPath: '/h/$slug'
      preLoaderRoute: typeof AuthenticatedHSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/houses/$slug': {
      id: '/_authenticated/account/houses/$slug'
      path: '/account/houses/$slug'
      fullPath: '/account/houses/$slug'
      preLoaderRoute: typeof AuthenticatedAccountHousesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedManageHousesRoute: typeof AuthenticatedManageHousesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHSlugRoute: typeof AuthenticatedHSlugRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountHousesSlugRoute: typeof AuthenticatedAccountHousesSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedManageHousesRoute: AuthenticatedManageHousesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHSlugRoute: AuthenticatedHSlugRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountHousesSlugRoute: AuthenticatedAccountHousesSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
