packages:
  - client/
  - server/
  - packages/*

catalog:
  '@eslint/js': ^10
  '@prisma/adapter-pg': 7.2.0
  '@prisma/client': 7.2.0
  '@types/node': ^22.19.11
  better-auth: ^1.6.9
  eslint: ^9
  eslint-config-prettier: ^10
  eslint-plugin-prettier: ^5.5
  globals: ^17.7
  prettier: ^3.8
  prisma: 7.2.0
  tsup: ^8.3
  tsx: ^4.19
  typescript: ^5.4
  typescript-eslint: ^8.6
  vite: ^8
  zod: ^4.3
