packages:
  - client
  - server
  - packages/types
  - packages/schemas

catalog:
  zod: ^4.3.6
  better-auth: ^1.6.9
  '@types/node': ^22.10.5
  '@prisma/adapter-pg': 7.2.0
  '@prisma/client': 7.2.0
  prisma: 7.2.0
  typescript: ^5.4.0
  eslint: ^9.39.2
