###

@PORT = 3000
@URL = http://localhost:{{PORT}}/api


### Health Check

GET {{URL}}/health HTTP/1.1
Content-Type: application/json

##############################################################################
### AUTHENTICATION
##############################################################################

### Sign out

POST {{URL}}/auth/sign-out HTTP/1.1
Content-Type: application/json


### Sign up with email/password

POST {{URL}}/auth/sign-up/email HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "name": "John Doe",
  "password": "password1234!"
}


### Sign in with email/password

POST {{URL}}/auth/sign-in/email HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password1234!"
}


##############################################################################
### USER
##############################################################################

### Get current user

# @attach-cookie-jar

GET {{URL}}/me HTTP/1.1


##############################################################################
### HOUSES
##############################################################################

@HOUSE_SLUG = test-house

### Get user houses

# @attach-cookie-jar

GET {{URL}}/auth/organization/list


### Get house members

# @attach-cookie-jar

GET {{URL}}/auth/organization/list-members?organizationSlug={{HOUSE_SLUG}}

### Create house

# @attach-cookie-jar

POST {{URL}}/auth/organization/create
Origin: http://localhost:5173
Content-Type: application/json

{
    "name": "test house",
    "slug": "test-house"
}


##############################################################################
### INVITE
##############################################################################

@INVITE_CODE = rhUyN7wR

### List house invites

# @attach-cookie-jar

GET {{URL}}/invites/list/{{HOUSE_SLUG}}?page=1&limit=10

### Get invite code info

# @attach-cookie-jar

GET {{URL}}/invites/{{INVITE_CODE}}


### Create invite link

# @attach-cookie-jar

POST {{URL}}/invites/create/{{HOUSE_SLUG}}
Content-Type: application/json

{
  "maxUses": 10
}


### Join house

# @attach-cookie-jar

POST {{URL}}/invites/{{INVITE_CODE}}/join


### Revoke invite

# @attach-cookie-jar

POST {{URL}}/invites/{{INVITE_CODE}}/revoke/{{HOUSE_SLUG}}
