###

@PORT = 3000
@URL = http://localhost:{{PORT}}/api


### Health Check

GET {{URL}}/health HTTP/1.1
Content-Type: application/json

##############################################################################
### AUTHENTICATION
##############################################################################

### Sign out

POST {{URL}}/auth/sign-out HTTP/1.1
Content-Type: application/json


### Sign up with email/password

POST {{URL}}/auth/sign-up/email HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "name": "John Doe",
  "password": "password1234!"
}


### Sign in with email/password

POST {{URL}}/auth/sign-in/email HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password1234!"
}


##############################################################################
### USER
##############################################################################

### Get current user

# @attach-cookie-jar

GET {{URL}}/me HTTP/1.1


##############################################################################
### HOUSES
##############################################################################

@HOUSE_ID = sbHDmAiiqYCwzI7nE0z7QDXNGSnO7aAC

### Get user houses

# @attach-cookie-jar

GET {{URL}}/auth/organization/list


### Create house

# @attach-cookie-jar

POST {{URL}}/auth/organization/create
Origin: http://localhost:5173
Content-Type: application/json

{
    "name": "test house",
    "slug": "test-house"
}


##############################################################################
### INVITE
##############################################################################

### Create invite link

# @attach-cookie-jar

POST {{URL}}/invites/create/{{HOUSE_ID}}
Content-Type: application/json

{
  "maxUses": 10,
  "expiresAt": "2026-12-31T23:59:59.000Z"
}

