###

@PORT = 3000
@URL = http://localhost:{{PORT}}/api


### Health Check

GET {{URL}}/health HTTP/1.1
Content-Type: application/json


### Sign up with email/password

POST {{URL}}/auth/sign-up/email HTTP/1.1
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "Test User",
  "password": "password123"
}


### Sign in with email/password

POST {{URL}}/auth/sign-in/email HTTP/1.1
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}


### Sign out

POST {{URL}}/auth/sign-out HTTP/1.1
Content-Type: application/json


### Get session (better-auth endpoint)

# @attach-cookie-jar

GET {{URL}}/auth/get-session HTTP/1.1


### Get current user

# @attach-cookie-jar

GET {{URL}}/me HTTP/1.1


### List all users

# @attach-cookie-jar

GET {{URL}}/users HTTP/1.1
